name: Trivy Scanner CI
on:
  push:
    branches:
      - main
env:
  # Authenticate with local/private registry. Can be ECR/ACR/GCR etc. 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Docker Registry authentication
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Docker Registry authentication

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -  name: Build an image from Dockerfile
         uses: docker/build-push-action@v5
         with:
          context: .
          file: ./Dockerfile-1
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/stalibali/clockbox:${{ github.sha }}'
          scan-type: image
          format: 'table'
          output: 'dependency-results.sbom.json'
          # exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          scanners: 'vuln,secret,config'
          severity: "LOW,MEDIUM,HIGH,CRITICAL"

      -  name: Push an image after scanning from Dockerfile
         uses: docker/build-push-action@v5
         with:
          context: .
          file: ./Dockerfile-1
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:${{ github.sha }}

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/dependency-results.sbom.json'
          retention-days: 1 # 90 is the default
      
      - uses: actions/upload-artifact@v3
        with:
         name: aqua-artifact
         path: out.*
