name: Secure Build with Aqua & GHAS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

jobs:
  build-and-secure:
    name: CI Build with Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t sample-app:latest .

      - name: Trivy FS Scan (Secrets + IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          format: table
          exit-code: 0

      - name: Trivy Image Scan (Fail on High/Critical)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sample-app:latest'
          severity: 'HIGH,CRITICAL'
          exit-code: 1
          format: table

      - name: Trivy SBOM Generation
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: cyclonedx
          output: sbom.cdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cdx.json

      - name: GHAS CodeQL Init
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: GHAS CodeQL Analyze
        uses: github/codeql-action/analyze@v3

      - name: Trivy SARIF Report for GitHub Security Tab
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
